# Generated by Django 4.1.7 on 2023-03-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(null=True, verbose_name='дата оплаты')),
                ('payment_sum', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('payment_type', models.CharField(choices=[('card', 'карта'), ('cash', 'наличные')], default='card', max_length=10, verbose_name='тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lern.course', verbose_name='Курс')),
            ],
        ),
    ]
