# Generated by Django 4.1.7 on 2023-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='Description',
            field=models.CharField(default='test', max_length=250, verbose_name='описание'),
        ),
    ]
