# Generated by Django 4.1.7 on 2023-03-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=250, verbose_name='название')),
                ('image', models.CharField(max_length=250, verbose_name='превью')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=250, verbose_name='название')),
                ('image', models.CharField(max_length=250, verbose_name='превью')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('view_link', models.CharField(max_length=500, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(null=True, verbose_name='дата оплаты')),
                ('payment_course', models.CharField(max_length=250, verbose_name='название оплаченного курса')),
                ('payment_sum', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('payment_type', models.CharField(choices=[('card', 'карта'), ('cash', 'наличные')], default='card', max_length=10, verbose_name='тип оплаты')),
            ],
        ),
    ]
