# Generated by Django 4.1.7 on 2023-03-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=250, verbose_name='название')),
                ('image', models.CharField(max_length=250, verbose_name='превью')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=250, verbose_name='название')),
                ('image', models.CharField(max_length=250, verbose_name='превью')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('view_link', models.CharField(max_length=500, verbose_name='ссылка на видео')),
                ('course_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lern.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
