# Generated by Django 4.1.7 on 2023-03-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lern', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='course_set',
        ),
    ]
