# Generated by Django 4.1.7 on 2023-03-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lern', '0004_course_owner_course_lesson_owner_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='owner_course',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='owner_lesson',
            new_name='owner',
        ),
    ]
